/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SHADOW_PB_H_INCLUDED
#define PB_SHADOW_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Shadow {
    bool on;
} Shadow;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Shadow_init_default                      {0}
#define Shadow_init_zero                         {0}

/* Field tags (for use in manual encoding/decoding) */
#define Shadow_on_tag                            4

/* Struct field encoding specification for nanopb */
#define Shadow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                4)
#define Shadow_CALLBACK NULL
#define Shadow_DEFAULT NULL

extern const pb_msgdesc_t Shadow_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Shadow_fields &Shadow_msg

/* Maximum encoded size of messages (where known) */
#define Shadow_size                              2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
